This commit was manufactured by cvs2svn to create tag 'GlastRelease-15-49-00'.
Sprout from master 2008-04-15 17:27:19 UTC burnett 'add flag (default disabled) to allow testing of aberration'
Cherrypick from master 2009-01-23 00:21:10 UTC ecephas 'Check in for GlastRelease-15-49-00':
    FluxSvcLib.py
    SConscript
Cherrypick from GLAST 2008-04-07 15:03:52 UTC glastrm 'AutoUpdate':
    ChangeLog
    cmt/Makefile
    doc/.cvsignore
Cherrypick from GlastReleasev15r49 2008-12-09 21:24:42 UTC ecephas 'Check in file.  Needed to resolve an undefined reference to __ctype_b for the shared library, FluxSvc. Documentation is in the file.':
    src/flux_c_type_fix.cxx
Delete:
    test_FluxSvc/.cvsignore
    test_FluxSvc/ChangeLog
    test_FluxSvc/cmt/.cvsignore
    test_FluxSvc/cmt/NMake
    test_FluxSvc/cmt/requirements
    test_FluxSvc/doc/release.notes
    test_FluxSvc/src/FluxTestAlg.cxx
    test_FluxSvc/src/flux/TimeDepSpectrum.cxx
    test_FluxSvc/src/flux/TimeDepSpectrum.h
    test_FluxSvc/src/flux/roottest.cxx
    test_FluxSvc/src/flux/testMgr.cxx
    test_FluxSvc/src/flux/test_library.xml
    test_FluxSvc/src/jobOptions.txt
    test_FluxSvc/src/testOptions.txt
    test_FluxSvc/src/test_source.xml