This commit was manufactured by cvs2svn to create tag 'v6r53gl1'.
Sprout from GlastReleasev15r49 2008-12-09 21:24:42 UTC ecephas 'Check in file.  Needed to resolve an undefined reference to __ctype_b for the shared library, FluxSvc. Documentation is in the file.'
Delete:
    .cvsignore
    ChangeLog
    FluxSvc/IFlux.h
    FluxSvc/IFluxSvc.h
    FluxSvc/IRegisterSource.h
    FluxSvc/ISpectrum.h
    FluxSvc/ISpectrumFactory.h
    FluxSvc/PointingInfo.h
    cmt/.cvsignore
    cmt/Makefile
    cmt/requirements
    data/ParticleTable.txt
    doc/.cvsignore
    doc/Doxyfile
    doc/FluxSvcDoc2.htm
    doc/FluxSvcFig1.jpg
    doc/FluxSvcFig2.jpg
    doc/release.notes
    src/Dll/FluxSvc_dll.cxx
    src/Dll/FluxSvc_load.cxx
    src/ExposureAlg.cxx
    src/ExposureAlg.h
    src/FluxAlg.cxx
    src/FluxAlg.h
    src/FluxSvc.cxx
    src/FluxSvc.h
    src/FluxSvcRandom.cxx
    src/OrbitSvc.cxx
    src/PointInfoAlg.cxx
    src/PointingInfo.cxx
    src/SAAboundary.txt
    src/defaultOptions.txt
    src/mainpage.h